//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLayer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceLayer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب.
        /// </summary>
        public static string BankAccount {
            get {
                return ResourceManager.GetString("BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت عابربانک.
        /// </summary>
        public static string BankCardNo {
            get {
                return ResourceManager.GetString("BankCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام بانک.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ ماشین.
        /// </summary>
        public static string CarColor {
            get {
                return ResourceManager.GetString("CarColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پلاک ماشین.
        /// </summary>
        public static string CarPlate {
            get {
                return ResourceManager.GetString("CarPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع ماشین.
        /// </summary>
        public static string CarType {
            get {
                return ResourceManager.GetString("CarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روی نقشه مشخص کن.
        /// </summary>
        public static string ClickMap {
            get {
                return ResourceManager.GetString("ClickMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست الکترونیکی.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره گواهینامه.
        /// </summary>
        public static string LicenseNo {
            get {
                return ResourceManager.GetString("LicenseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن همراه.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدملی.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمزعبور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام کنید.
        /// </summary>
        public static string RegisterIt {
            get {
                return ResourceManager.GetString("RegisterIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرا به خاطرت نگهدار.
        /// </summary>
        public static string RemeberMe {
            get {
                return ResourceManager.GetString("RemeberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساس به حروف بزرگ و کوچک.
        /// </summary>
        public static string SensitivePassword {
            get {
                return ResourceManager.GetString("SensitivePassword", resourceCulture);
            }
        }
    }
}
